### ISSUE TITLE
Drop Portfolio Version command

### ISSUE THREAD

**Issue by ignar** [ftt-project/ftt#113]
### What is the reason to work on this?

As a user
When I create multiple portfolio versions, 
Or have a portfolio version which I don't need anymore
I want to drop the portfolio version.

Because it is a finance system, the data must be retained and erased carefully, and never to be really deleted.
For this purpose, we must use soft delete.

### What value will it bring?

Ability to retain data, undo deletion operation.

### Acceptance criteria?

- [ ] `portfolio-versions delete portfolio-id=`
- [ ] use safe delete for portfolio versions

### Subtickets

- [ ] Update portfolio version model
- [ ] Update repository
- [ ] Create `PortfolioVersionDeleteStep`
- [ ] Create PortfolioVersionDeletionHandler
- [ ] Create `PortfoliosCommands.delete` command
- [ ] Hide delete portfolio versions from user
